macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  script: |
     brew update
     brew install objc-codegenutils objc-run
     brew install git python cmake fftw gcc qt5 lcov pkg-config zlib cmake libtiff cfitsio hdf5 gsl clfft pandoc llvm go
     brew install iltommi/brews/hdf4
     mkdir -p build_gcc && cd build_gcc
     cmake -DCMAKE_CXX_COMPILER=g++-12 -DQt5_DIR=`brew --prefix qt@5`/lib/cmake/Qt5 -DNEUTRINO_SKIP_PLUGINS=Shell ..
     make -j$(sysctl -n hw.ncpu) install
     ../resources/macPackage/prepareapp.sh
     cp Neutrino-Darwin-arm64.* ..
  m1_artifacts:
    path: "Neutrino-Darwin-arm64.*"


