MacIntel_task:
  only_if: $CIRRUS_BRANCH == 'master'
  macos_instance:
    image: big-sur-base
  script: |
    brew update
    brew install objc-codegenutils objc-run gh create-dmg
    brew install libomp git cmake fftw gcc qt lcov pkg-config zlib cmake libtiff cfitsio hdf5 gsl clfft pandoc
    brew install iltommi/brews/hdf4
    mkdir -p build && cd build
    cmake ..
    make -j$(sysctl -n hw.ncpu) install
    ../resources/macPackage/prepareapp.sh
    gh release upload --clobber latest Neutrino*.dmg
    gh release edit latest -n "build info: https://cirrus-ci.com/build/$CIRRUS_BUILD_ID"
    cp Neutrino-*.dmg ..
  artifacts:
    path: "Neutrino*.dmg"

MacM1_task:
  only_if: $CIRRUS_BRANCH == 'master'
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  script: |
    brew update
    brew install objc-codegenutils objc-run gh create-dmg
    brew install libomp git cmake fftw gcc qt lcov pkg-config zlib cmake libtiff cfitsio hdf5 gsl clfft pandoc
    brew install iltommi/brews/hdf4
    mkdir -p build && cd build
    cmake ..
    make -j$(sysctl -n hw.ncpu) install
    ../resources/macPackage/prepareapp.sh
    gh release upload --clobber latest Neutrino*.dmg
    cp Neutrino-*.dmg ..
  artifacts:
    path: "Neutrino*.dmg"

AppImage_task:
  only_if: $CIRRUS_BRANCH == 'master'
  container:
    image: fedora:36
  env:
    VERSION: Linux
    APPIMAGE_EXTRACT_AND_RUN: 1
    LD_LIBRARY_PATH: AppDir/usr/lib
  script: |
    dnf -y install gcc gcc-c++ qconf libtiff-devel gsl-devel redhat-lsb-core blas-devel pandoc hdf-devel hdf5-devel cfitsio-devel fftw3-devel rpm-build qt6-* git wget gh
    wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage 
    wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
    chmod +x linuxdeploy*.AppImage
    mkdir build && cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    make install DESTDIR=AppDir
    ../linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage --custom-apprun=../resources/linuxPackage/AppRun --icon-file=../resources/icons/neutrino.svg
    cp Neutrino-*.AppImage ..
    gh release upload --clobber latest Neutrino-*.AppImage
  artifacts:
    path: "Neutrino-*.AppImage"

Cross32_task:
  only_if: $CIRRUS_BRANCH == 'master'
  container:
    image: fedora:36
  script: |
    dnf clean all
    dnf -y --nogpgcheck update
    dnf -y install cmake git mingw32-qt6* mingw32-gcc-c++ mingw32-gcc mingw32-gcc-gfortran mingw32-libgomp mingw32-gsl mingw32-zlib mingw32-nsis unzip wget autoconf automake bash bison bzip2 flex gcc-c++ gdk-pixbuf2-devel gettext git gperf intltool make sed libffi-devel libtool openssl-devel p7zip patch perl pkgconfig python ruby scons unzip wget xz gtk-doc dh-autoreconf mingw32-portablexdr pandoc mingw32-cfitsio gh
    wget http://www.fftw.org/fftw-3.3.6-pl2.tar.gz
    tar -zxvf fftw-3.3.6-pl2.tar.gz
    cd fftw-3.3.6-pl2
    mingw32-configure --disable-static --enable-shared --enable-threads --with-combined-threads 
    make bin_PROGRAMS= sbin_PROGRAMS= noinst_PROGRAMS= 
    make install bin_PROGRAMS= sbin_PROGRAMS= noinst_PROGRAMS=  
    cd ..
    wget https://support.hdfgroup.org/ftp/HDF/releases/HDF4.2.10/src/hdf-4.2.10.tar.bz2
    tar -jxvf hdf-4.2.10.tar.bz2 && cd hdf-4.2.10
    wget https://raw.githubusercontent.com/iltommi/mxe/master/src/hdf4-1-portability-fixes.patch
    wget https://raw.githubusercontent.com/iltommi/mxe/master/src/hdf4-2-dllimport.patch
    patch -p1 -u < hdf4-1-portability-fixes.patch
    patch -p1 -u < hdf4-2-dllimport.patch
    libtoolize --force
    autoreconf --install
    mingw32-configure --disable-static --enable-shared --disable-fortran --disable-netcdf LIBS="-lportablexdr -lws2_32"  CPPFLAGS="-DH4_F77_FUNC\(name,NAME\)=NAME -DH4_BUILT_AS_DYNAMIC_LIB=1 -DBIG_LONGS"
    make -C mfhdf/xdr LDFLAGS="-no-undefined -lssp"
    make -C hdf/src LDFLAGS="-no-undefined -lssp"
    make -C hdf/src install
    make -C mfhdf/libsrc LDFLAGS="-no-undefined -ldf"
    make -C mfhdf/libsrc install
    cd ..
    mkdir build && cd build
    mingw32-cmake -DNEUTRINO_SKIP_PLUGINS='Function' ..
    make -j2 package
    gh release upload --clobber latest Neutrino*.exe
    cp Neutrino*.exe Neutrino*.zip ..
  artifacts:
    path: "Neutrino-*.*"


Cross64_task:
  only_if: $CIRRUS_BRANCH == 'master'
  container:
      image: fedora:36
  script: |
    dnf clean all
    dnf -y --nogpgcheck update
    dnf -y install cmake git mingw64-qt6* mingw64-gcc-c++ mingw64-gcc-gfortran mingw64-libgomp mingw64-gsl mingw64-zlib mingw32-nsis unzip wget autoconf automake bash bison bzip2 flex gcc-c++ gdk-pixbuf2-devel gettext git gperf intltool make sed libffi-devel libtool openssl-devel p7zip patch perl pkgconfig python ruby scons unzip wget xz gtk-doc dh-autoreconf mingw64-portablexdr pandoc mingw64-cfitsio gh
    wget http://www.fftw.org/fftw-3.3.6-pl2.tar.gz
    tar -zxvf fftw-3.3.6-pl2.tar.gz
    cd fftw-3.3.6-pl2
    mingw64-configure --disable-static --enable-shared --enable-threads --with-combined-threads
    make -j bin_PROGRAMS= sbin_PROGRAMS= noinst_PROGRAMS=    
    make install bin_PROGRAMS= sbin_PROGRAMS= noinst_PROGRAMS=   
    cd ..
    wget https://support.hdfgroup.org/ftp/HDF/releases/HDF4.2.10/src/hdf-4.2.10.tar.bz2
    tar -jxvf hdf-4.2.10.tar.bz2 && cd hdf-4.2.10
    wget https://raw.githubusercontent.com/iltommi/mxe/master/src/hdf4-1-portability-fixes.patch
    wget https://raw.githubusercontent.com/iltommi/mxe/master/src/hdf4-2-dllimport.patch
    patch -p1 -u < hdf4-1-portability-fixes.patch
    patch -p1 -u < hdf4-2-dllimport.patch 
    libtoolize --force
    autoreconf --install
    mingw64-configure --disable-static --enable-shared --disable-fortran --disable-netcdf LIBS="-lportablexdr -lws2_32"  CPPFLAGS="-DH4_F77_FUNC\(name,NAME\)=NAME -DH4_BUILT_AS_DYNAMIC_LIB=1 -DBIG_LONGS"
    make -C mfhdf/xdr LDFLAGS="-no-undefined -lssp"
    make -C hdf/src LDFLAGS="-no-undefined -lssp"
    make -C hdf/src install
    make -C mfhdf/libsrc LDFLAGS="-no-undefined -ldf"
    make -C mfhdf/libsrc install
    cd ..
    mkdir build && cd build
    mingw64-cmake ..
    make -j2 package
    gh release upload --clobber latest Neutrino*.exe
    cp Neutrino*.exe Neutrino*.zip ..      
  artifacts:
    path: "Neutrino-*.*"
