language: cpp

os: osx
osx_image: xcode7.3

before_install:
 - export MACOSX_DEPLOYMENT_TARGET=10.11
 - brew update; brew tap homebrew/science
 - brew install gcc qt5 cfitsio cmake hdf4 hdf5 gsl netpbm clfft pandoc
 - brew install fftw --with-openmp
 - git clone https://github.com/iltommi/PythonQt.git
 - cd PythonQt
 - mkdir my_build && cd my_build
 - cmake -DCMAKE_CXX_COMPILER=g++-6  -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -UQT_QMAKE_EXECUTABLE -DPythonQt_Wrap_QtAll=TRUE ..
 - make install
 - cd ../..

script:
 - mkdir -p build_dir && cd build_dir
 - cmake -DCMAKE_CXX_COMPILER=g++-6  -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5  ..
 - make
 - cd ..

install:

before_deploy:
 - cp -r build_dir/Neutrino.app .
 - /usr/local/opt/qt5/bin/macdeployqt Neutrino.app
 - git clone https://github.com/iltommi/macdeployqtfix.git
 - python macdeployqtfix/macdeployqtfix.py Neutrino.app/Contents/MacOS/Neutrino /usr/local
 - /usr/libexec/PlistBuddy -c "Add NSHighResolutionCapable bool True" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes array" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0 dict" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeName string Neutrino session" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeRole string Viewer" Neutrino.app/Contents/Info.plist
 - cp resources/macPackage/filetype.icns Neutrino.app/Contents/Resources
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeIconFile string filetype.icns" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions array" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions:0 string neus" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions:1 string neu" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions:2 string fits" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions:3 string tiff" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions:4 string hdf" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions:5 string img" Neutrino.app/Contents/Info.plist
 - /usr/libexec/PlistBuddy -c "Add :CFBundleDocumentTypes:0:CFBundleTypeExtensions:0 string sif" Neutrino.app/Contents/Info.plist
 - mkdir dmg
 - mv Neutrino.app dmg
 - export RELEASE_FILE=Neutrino.dmg
 - ./resources/macPackage/createdmg.sh --icon-size 96 --volname Neutrino --volicon resources/macPackage/dmg-icon.icns --background resources/macPackage/background.png --window-size 420 400 --icon Neutrino.app 90 75 --app-drop-link 320 75 Neutrino.dmg dmg
  
after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" = false ]
  then
    git config --global user.email "builds@travis-ci.com"
    git config --global user.name "Travis CI"
    git tag -fa latest -m "Travis build $TRAVIS_BUILD_NUMBER"
    git push origin --tags
    git fetch origin
  fi
  
  
deploy:
  provider: releases
  edge:
    branch: releases-fix
  api_key: $github_token
  file_glob: true
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  overwrite: true
  on:
    tags: false
    branch: master
