language: cpp

os: osx
osx_image: xcode9.2

branches:
  only:
  - master
  - latest
  
git:
  depth: 9999999
  
before_install:
 - brew update; brew tap iltommi/brews
 - brew install --only-dependencies gcc
 - brew cask uninstall oclint
 - brew install gcc qt5 cfitsio hdf4 hdf5 gsl clfft pandoc
 - brew install fftw --with-openmp
 - mkdir my_build && cd my_build
 - cmake -DCMAKE_CXX_COMPILER=g++-7 -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -UQT_QMAKE_EXECUTABLE -DPythonQt_Wrap_QtAll=TRUE ../PythonQt
 - make install
 - cd ..

script:
 - mkdir -p build_dir && cd build_dir
 - cmake -DCMAKE_CXX_COMPILER=g++-7 ..
 - make

install:

before_deploy:
 - ../resources/macPackage/prepareapp.sh
    
deploy:
  provider: releases
  api_key: $github_token
  file_glob: true
  file: "Neutrino.dmg"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branch: master
