language: cpp

os:
  - linux
  - osx

sudo: required
dist: trusty
osx_image: xcode7.2

          
before_install:
  - git fetch -t
  - git clone https://github.com/commontk/PythonQt.git
  - cd PythonQt
  - mkdir -p compile && cd compile
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 .. && make && make install; fi
  - cd ../..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa; sudo apt-get update -qq; fi
  # neutrino
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y cmake g++ libcfitsio3-dev libhdf5-dev libtiff5-dev libfftw3-dev libfftw3-3 libgsl0-dev gsl-bin libhdf4-dev build-essential; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew upgrade && brew tap homebrew/science; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc qt5 cfitsio cmake hdf4 hdf5 gsl; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew info fftw; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install fftw --with-openmp; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew list; fi

script:
  - git checkout -b travis
  - git tag -a v1.0 -m "travis 1.0"
  - make

install:
