language: cpp

os: 
 - osx
 - linux
 
matrix:
  exclude:
    - os: osx
  allow_failures:
    - os: linux
  
sudo: required
dist: trusty

osx_image: xcode7.1

before_install:
  - echo $COMPILER
  - echo $Qt5_DIR
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]
    then
        export COMPILER=g++-6
        export Qt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5
        brew update; brew tap homebrew/science
        brew install gcc qt5 cfitsio cmake hdf4 hdf5 gsl
        brew install fftw --with-openmp; 
    else
        export COMPILER=g++
        sudo apt-get install -yy build-essential
        git clone git@github.com:Kitware/CMake.git
        cd CMake
        ./configure
        make
        sudo make install
        sudo updatedb
        locate Qt5Config.cmake
        export Qt5_DIR=/usr/share/qt5/lib/cmake/Qt5
        sudo apt-get -yy update
        sudo apt-get -yy upgrade
        sudo apt-get -yy install qt5
        sudo apt-get -yy install fftw
    fi
  - git clone https://github.com/iltommi/PythonQt.git
  - cd PythonQt
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DQt5_DIR=$Qt5_DIR -UQT_QMAKE_EXECUTABLE -DPythonQt_Wrap_QtAll=TRUE .
  - make 
  - make install
  - cd ..

script:
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DQt5_DIR=$Qt5_DIR .
  - make

install:

before_deploy:
  - export RELEASE_FILE=Neutrino.dmg
  - /usr/local/opt/qt5/bin/macdeployqt Neutrino.app
  - git clone https://github.com/iltommi/macdeployqtfix.git
  - python macdeployqtfix/macdeployqtfix.py Neutrino.app/Contents/MacOS/Neutrino /usr/local
  - /usr/libexec/PlistBuddy -c "Add NSHighResolutionCapable bool True" Neutrino.app/Contents/Info.plist
  - mkdir dmg
  - mv Neutrino.app dmg
  - ./resources/macPackage/createdmg.sh --icon-size 96 --volname Neutrino --volicon resources/icons/icon.icns --background resources/macPackage/sfondo.png --window-size 420 400 --icon Neutrino.app 90 75 --app-drop-link 320 75 Neutrino.dmg dmg

deploy:
  provider: releases
  api_key: $github_token
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
