language: cpp

os: osx
osx_image: xcode7.3

branches:
  only:
  - master
  - latest
  
git:
  depth: 9999999
  
before_install:
 - export MACOSX_DEPLOYMENT_TARGET=10.11
 - brew update; brew tap homebrew/science
 - brew install gcc qt5 cfitsio hdf4 hdf5 gsl clfft pandoc
 - brew install fftw --with-openmp
 - git clone https://github.com/iltommi/PythonQt.git
 - cd PythonQt
 - mkdir my_build && cd my_build
 - cmake -DCMAKE_CXX_COMPILER=g++-7  -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5 -UQT_QMAKE_EXECUTABLE -DPythonQt_Wrap_QtAll=TRUE ..
 - make install
 - cd ../..

script:
 - mkdir -p build_dir && cd build_dir
 - cmake -DCMAKE_CXX_COMPILER=g++-7  -DQt5_DIR=/usr/local/opt/qt5/lib/cmake/Qt5  ..
 - make

install:

before_deploy:
 - ../resources/macPackage/prepareapp.sh .
    
deploy:
  provider: releases
  api_key: $github_token
  file_glob: true
  file: "Neutrino.dmg"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branch: master
