language: cpp

os: 
 - osx
 - linux
 
matrix:
  exclude:
    - os: osx
  allow_failures:
    - os: linux
  
sudo: required
dist: trusty

osx_image: xcode7.1

before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt561-trusty
  - sudo apt-get update -qy
  - sudo apt-get install -y qt56base qt56multimedia qt56script qt56svg qt56tools
  - sudo updatedb
  - locate -q Qt5Config.cmake 2> /dev/null
  - sudo apt-get install -y libfftw3-dev
  - sudo apt-get install -y libnetpbm10-dev
  - sudo apt-get install -y libgsl0-dev
  - sudo apt-get install -y libhdf5-dev
  - sudo apt-get install -y libhdf4-dev
  - sudo apt-get install -y libpython-dev
  - git clone https://github.com/iltommi/PythonQt.git
  - cd PythonQt
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DQt5_DIR=$Qt5_DIR -UQT_QMAKE_EXECUTABLE -DPythonQt_Wrap_QtAll=TRUE .
  - make 
  - make install
  - cd ..

script:
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER -DQt5_DIR=$Qt5_DIR .
  - make

install:

before_deploy:
  - export RELEASE_FILE=Neutrino.dmg
  - /usr/local/opt/qt5/bin/macdeployqt Neutrino.app
  - git clone https://github.com/iltommi/macdeployqtfix.git
  - python macdeployqtfix/macdeployqtfix.py Neutrino.app/Contents/MacOS/Neutrino /usr/local
  - /usr/libexec/PlistBuddy -c "Add NSHighResolutionCapable bool True" Neutrino.app/Contents/Info.plist
  - mkdir dmg
  - mv Neutrino.app dmg
  - ./resources/macPackage/createdmg.sh --icon-size 96 --volname Neutrino --volicon resources/icons/icon.icns --background resources/macPackage/sfondo.png --window-size 420 400 --icon Neutrino.app 90 75 --app-drop-link 320 75 Neutrino.dmg dmg

deploy:
  provider: releases
  api_key: $github_token
  file: "${RELEASE_FILE}"
  skip_cleanup: true
  on:
    tags: true
