#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export QT_PLUGIN_PATH="${HERE}/usr/lib/qt5/plugins"
export LD_LIBRARY_PATH="${HERE}/usr/lib/:${LD_LIBRARY_PATH}"
export PATH="${HERE}/usr/bin:${PATH}"
exec "${HERE}/usr/bin/Neutrino" "$@"
cd -
