#! /usr/bin/env bash
# make sure errors in sourced scripts will cause this script to stop
set -e

this_dir="$(readlink -f "$(dirname "$0")")"

source "$this_dir"/apprun-hooks/"linuxdeploy-plugin-qt-hook.sh"

export LD_LIBRARY_PATH="$this_dir"/usr/lib

exec "$this_dir"/usr/bin/Neutrino "$@"

