name: macosBuild

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: prepare build
      run: |
        brew update
        brew install objc-codegenutils objc-run create-dmg
        brew install libomp git cmake fftw gcc qt lcov pkg-config zlib cmake libtiff cfitsio hdf5 gsl clfft pandoc vulkan-headers
        brew install iltommi/brews/hdf4
        mkdir -p build && cd build
        cmake .. -DCMAKE_CXX_FLAGS="-I$(brew --prefix libomp)/include" -DCMAKE_EXE_LINKER_FLAGS="-L$(brew --prefix libomp)/lib"
        make -j$(sysctl -n hw.ncpu) install
        ../resources/macPackage/prepareapp.sh
    - name: upload
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "build/Neutrino*.dmg"
        update_latest_release: true
        overwrite: true
    
