name: macIntel

on:
  push:
    branches:    
      - *

jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Tag latest
      uses: EndBug/latest-tag@latest
      with:
        description: Latest
    - name: Prepare
      run: |
        brew install objc-codegenutils objc-run create-dmg
        brew install libomp git cmake fftw gcc qt lcov pkg-config zlib cmake libtiff cfitsio hdf5 gsl clfft pandoc vulkan-headers
    - name: Deps
      run: |
        brew install --force iltommi/brews/hdf4
    - name: Build
      run: |
        mkdir -p build && cd build
        cmake .. -DCMAKE_CXX_FLAGS="-I$(brew --prefix libomp)/include" -DCMAKE_EXE_LINKER_FLAGS="-L$(brew --prefix libomp)/lib"
        make -j$(sysctl -n hw.ncpu) install
        ../resources/macPackage/prepareapp.sh
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: Neutrino.dmg
        path: "build/Neutrino*.dmg"
    - name: Upload
      if: github.ref == 'refs/heads/master'
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "build/Neutrino*.dmg"
        update_latest_release: true
        overwrite: true
    
