name: macIntel

on: push
jobs:
  build:
    runs-on: macos-12
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Tag latest
      uses: EndBug/latest-tag@latest
      with:
        description: Latest
    - name: Prepare
      run: |
        brew install objc-codegenutils objc-run
        brew install libomp git cmake fftw gcc qt lcov pkg-config zlib cmake libtiff cfitsio hdf5 gsl pandoc vulkan-headers
    - name: Deps
      run: |
        brew install --force iltommi/brews/hdf4
        brew install --force iltommi/brews/clfft
    - name: PyhtonQt
      run: |
        git clone https://github.com/iltommi/pythonqt.git
        cd pythonqt
        wget https://www.python.org/ftp/python/3.12.2/Python-3.12.2.tgz
        tar -zxf Python-3.12.2.tgz
        cd Python-3.12.2
        ./configure --prefix=$(pwd)/../python
        make -j$(sysctl -n hw.ncpu)
        make install
        cd ..
        find python/bin
        cd generator
        qmake -r generator.pro
        make -j10
        QTDIR=$(brew --prefix qt) ./pythonqt_generator
        cd ..
        PYTHON_VERSION=$(./python/bin/python3 --version | cut -d " " -f 2 | cut -d "." -f1,2) PYTHON_DIR=$(pwd)/python QTDIR=$(brew --prefix qt) qmake -r
        make -j10
        INSTALL_ROOT=$(brew --prefix) make install
        cd ..
      continue-on-error: true
    - name: Build
      run: |
        mkdir -p build && cd build
        cmake ..
        make -j$(sysctl -n hw.ncpu) install
        ../resources/macPackage/prepareapp.sh
    - name: Archive
      uses: actions/upload-artifact@v3
      with:
        name: Neutrino.zip
        path: "build/Neutrino*.zip"
    - name: Upload
      if: github.ref == 'refs/heads/master'
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "build/Neutrino*.zip"
        update_latest_release: true
        overwrite: true
    
